#!/usr/bin/env bash

options=" Lock
 Suspend
 Reboot
 Shutdown
 Logout"

selected=$(echo "$options" | tofi --prompt-text "Power: ")

case "$selected" in
    *Lock)      hyprlock ;;
    *Suspend)   systemctl suspend ;;
    *Reboot)    systemctl reboot ;;
    *Shutdown)  systemctl poweroff ;;
    *Logout)    hyprctl dispatch exit ;;
esac
