require("settings")
require("mappings")
require("plugins/list")
require("plugins/lualine")
require("plugins/lsp")
require("plugins/toggleterm")
require("plugins/treesitter")
require("plugins/indentline")
require("plugins/telescope_configuration")
-- require("plugins/lspsaga")
-- require("plugins/nvimtree")
require("colors/colorscheme")

