# Catppuccin Mocha
format = """
[](crust)\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$status\
$line_break\
$character\
"""

palette = "mocha"

[palettes.mocha]
base      = "#1e1e2e"
crust     = "#11111b"
text      = "#cdd6f4"
subtext0  = "#a6adc8"
subtext1  = "#bac2de"
surface0  = "#313244"
surface1  = "#45475a"
surface2  = "#585b70"
overlay0  = "#6c7086"
blue      = "#89b4fa"
lavender  = "#b4befe"
mauve     = "#cba6f7"
green     = "#a6e3a1"
yellow    = "#f9e2af"
peach     = "#fab387"
red       = "#f38ba8"
teal      = "#94e2d5"
pink      = "#f5c2e7"

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vicmd_symbol   = "[❮](mauve)"

[directory]
style  = "blue"
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
"$HOME"      = "~"
"$HOME/Documents" = "Docs"
"$HOME/Downloads" = "Dls"

[git_branch]
symbol = " "
style  = "peach"
format = "[$symbol$branch]($style)"

[git_status]
style  = "peach"
format = '[$all_status$ahead_behind]($style)'

[cmd_duration]
style  = "yellow"
format = "[$duration]($style)"
min_time = 2000

[status]
style     = "red"
symbol    = "✗"
disabled  = false
format    = "[$symbol$status]($style)"

[fill]
symbol = " "

[golang]
style   = "blue"
format  = "[$symbol$version]($style)"
