# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

general {
    gaps_in = 4     # Gap between windows
    gaps_out = 5   # Gap between windows and screen edges
}

animations {
    enabled = false
}

dwindle {
    split_bias = 1    # positive = right/bottom, negative = left/top
}   

input {
    repeat_rate = 70
    repeat_delay = 200

    touchpad {
      scroll_factor = 0.4
    }
}

decoration {
  rounding = 4

  dim_inactive = true
  dim_strength = 0.25

  active_opacity = 0.9
  inactive_opacity = 0.8
}

$SUPER = SUPER
$terminal = foot
# $terminal = kitty
$fileManager = yazi
$menu = wofi
$browser = brave

bind = $SUPER, RETURN, exec, $terminal
bind = $SUPER_SHIFT, RETURN, exec, $browser
bind = $SUPER, Q, killactive,
bind = $SUPER, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $SUPER, P, exec, /home/mbv/.local/bin/screenshot
bind = $SUPER, ESCAPE, exec, hyprlock

# Universal copy/paste/cut (omarchy-style)
bind = $SUPER, C, sendshortcut, CTRL, Insert, activewindow
bind = $SUPER, V, sendshortcut, SHIFT, Insert, activewindow
bind = $SUPER, X, sendshortcut, CTRL, X, activewindow
# bindd = SUPER CTRL, V, Clipboard manager, exec, walker -m clipboard  # needs 'walker' installed
bind = $SUPER, F, exec, $terminal bash -c $fileManager
bind = $SUPER, T, togglefloating,
bind = $SUPER, SPACE, exec, $menu
bind = $SUPER_SHIFT, F, fullscreen, 1

bind = $SUPER, minus, resizeactive, -50 0
bind = $SUPER, equal, resizeactive, 50 0
bind = $SUPER_SHIFT, minus, resizeactive, 0 -50
bind = $SUPER_SHIFT, equal, resizeactive, 0 50

bind = $SUPER, H, movefocus, l
bind = $SUPER, L, movefocus, r
bind = $SUPER, K, movefocus, u
bind = $SUPER, J, movefocus, d

bind = $SUPER_SHIFT, H, movewindow, l
bind = $SUPER_SHIFT, L, movewindow, r
bind = $SUPER_SHIFT, K, movewindow, u
bind = $SUPER_SHIFT, J, movewindow, d

bind = $SUPER, 1, workspace, 1
bind = $SUPER, 2, workspace, 2
bind = $SUPER, 3, workspace, 3
bind = $SUPER, 4, workspace, 4
bind = $SUPER, 5, workspace, 5
bind = $SUPER, 9, workspace, 9

bind = $SUPER_SHIFT, code:10, movetoworkspacesilent, 1
bind = $SUPER_SHIFT, code:11, movetoworkspacesilent, 2
bind = $SUPER_SHIFT, code:12, movetoworkspacesilent, 3
bind = $SUPER_SHIFT, code:13, movetoworkspacesilent, 4
bind = $SUPER_SHIFT, code:14, movetoworkspacesilent, 5
bind = $SUPER_SHIFT, code:15, movetoworkspacesilent, 6
bind = $SUPER_SHIFT, code:16, movetoworkspacesilent, 7
bind = $SUPER_SHIFT, code:17, movetoworkspacesilent, 8
bind = $SUPER_SHIFT, code:18, movetoworkspacesilent, 9
bind = $SUPER_SHIFT, code:19, movetoworkspacesilent, 10

env = GDK_SCALE,1
env = GDK_BACKEND,wayland
monitor = eDP-1, 1920x1080@60, auto, 1

# exec-once=waybar
exec-once = bash -c "sleep 1 && waybar"
exec-once = awww-daemon
exec-once = sleep 0.5 && awww img ~/wallpapers/mesmeric-forest-live.gif
