return {
			--  "robitx/gp.nvim",
			--  config = function()
			--      local conf = {
			--          -- For customization, refer to Install > Configuration in the Documentation/Readme
			-- providers = {
			-- 	anthropic = {
			-- 		endpoint = "https://api.anthropic.com/v1/messages",
			-- 		secret = os.getenv("ANTHROPIC_API_KEY"),
			-- 	},
			-- 	-- copilot = { 
			-- 	-- 		disable = false, 
			-- 	-- 		endpoint = "https://api.githubcopilot.com/chat/completions", 
			-- 	-- 		secret = { 
			-- 	-- 			"bash", 
			-- 	-- 			"-c", 
			-- 	-- 			"cat ~/.config/github-copilot/apps.json | sed -e 's/.*oauth_token...//;s/\".*//'", 
			-- 	-- 		}, 
			-- 	-- 	}, 
			-- }
			--      }
			--      require("gp").setup(conf)
			--
			--      -- Setup shortcuts here (see Usage > Shortcuts in the Documentation/Readme)
			--  end,
}
